# Site
repository: newbisi/newbisi.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tobias Jawecki
title: Mathematics Researcher
email: tobias.jawecki@gmail.com
website: https://newbisi.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  newbisi
orcid_username: 0000-0002-5720-3613
googlescholar_username: u1dLQx0AAAAJ

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi.

  <a href="https://github.com/newbisi/newbisi.github.io/raw/main/pdf/CV_TobiasJawecki.pdf"> <i class="fa fa-file-pdf-o"></i>  Download CV</a>

content:
  - title: Software
    layout: list
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: smallexpimv
        link: https://github.com/newbisi/smallexpimv
        link_text: Github page
        description: | # this will include new lines to allow paragraphs
          Python package for subroutines used by unitary Krylov propagators. Based on Fortran code using blas and lapack libraries. Also available in the pypi package manager. 
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: adaptive Magnus-Krylov propagators
        description: | # this will include new lines to allow paragraphs
          Fortran and python code, to be published.

  - title: Publication List
    layout: list
    content:

      - layout: top
        border: 0
        title: Preprints
        description: |
          - T. Jawecki and P. Singh. Unitarity of some barycentric rational approximants, 2022.
            preprint at <a href="https://arxiv.org/abs/2205.10606">https://arxiv.org/abs/2205.10606</a>
          - T. Jawecki. A review of the separation theorem of Chebyshev-Markov-Stieltjes for polynomial and some rational Krylov subspaces, 2022.
            preprint at <a href="https://arxiv.org/abs/2205.01535">https://arxiv.org/abs/2205.01535</a>

      - layout: top
        border: 0
        title: Publications
        description: |
          - W. Auzinger, T. Jawecki, O. Koch, P. Pukach, R. Stolyarchuk, and E.B. Weinmüller.
            Efficient Magnus-type integrators for solar energy conversion in Hubbard models.
            J. Comput. Math. Data Sci., 2:100018, 2022.
            doi <a href="https://doi.org/10.1016/j.jcmds.2021.100018">10.1016/j.jcmds.2021.100018</a>
          - T. Jawecki.
            A study of defect-based error estimates for the Krylov approximation of phi-functions.
            Numer. Algorithms, 90(1):323--361, 2022.
            doi <a href="https://doi.org/10.1007/s11075-021-01190-x">10.1007/s11075-021-01190-x</a>
          - C. Schattauer, L. Linhart, T. Fabian, T. Jawecki, W. Auzinger, and F. Libisch.
            Graphene quantum dot states near defects.
            Phys. Rev. B, 102:155430, 2020.
            doi <a href="https://doi.org/10.1103/PhysRevB.102.155430">10.1103/PhysRevB.102.155430</a>
          - T. Jawecki, W. Auzinger, and O. Koch.
            Computable upper error bounds for {K}rylov approximations to matrix exponentials and associated phi-functions. BIT, 60(1):157--197, 2020.
            doi <a href="https://doi.org/10.1007/s10543-019-00771-6">10.1007/s10543-019-00771-6</a>

      - layout: top
        border: 0
        title: Conference Papers
        description: |
          - W. Auzinger, T. Jawecki, O. Koch, P. Pukach, R. Stolyarchuk, and E.B. Weinmüller.
            Some aspects on [numerical] stability of evolution equations of stiff type; use of computer algebra.
            In 2021 IEEE XVII th International Conference on the Perspective Technologies and Methods in MEMS Design (MEMSTECH), pages 180--184, 2021.
            doi <a href="https://doi.org/10.1109/memstech53091.2021.9468055">10.1109/memstech53091.2021.9468055</a>

      - layout: top
        border: 0
        title: Theses
        description: |
          - T. Jawecki.
            Krylov techniques and approximations to the action of matrix exponentials.
            Ph.D thesis, TU Wien, Austria, 2022.
            doi <a href="https://doi.org/10.34726/hss.2022.45083"> 10.34726/hss.2022.45083 </a>
          - T. Jawecki. Bifurcation analysis via numerical continuation for nonlinear fourth-order partial differential equations. Diploma thesis, TU Wien, 2017.
            available online at <a href="http://katalog.ub.tuwien.ac.at/AC13642458"> http://katalog.ub.tuwien.ac.at/AC13642458 </a>



# Footer
footer_show_references: true
references_title: using sproogen/modern-resume-theme

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
