# Site
repository: newbisi/newbisi.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tobias Jawecki
title: Mathematics Researcher
email: tobias.jawecki@gmail.com
website: https://newbisi.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  newbisi
orcid_username: 0000-0002-5720-3613
googlescholar_username: u1dLQx0AAAAJ

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  I received my PhD in numerical mathematics at TU Wien.
  The main topics of my PhD thesis are Krylov techniques and approximations to the action of matrix exponentials.
  While my research mainly revolves around numerical analysis and computational mathematics, I also enjoy working on applications and development of numerical software.
  As a PhD student I was part of the doctoral college <a href="http://dollywood.itp.tuwien.ac.at/~florian/tu_d_page/faculty" >Unravelling Advanced 2D Materials (TU-D)</a>,
  which led to interdisciplinary collaborations focusing on time integration of quantum systems.

  Some of my research collaborators are
  <a href="https://www.asc.tuwien.ac.at/~winfried/" >Winfried Auzinger</a> (doctoral advisor),
  <a href="http://dollywood.itp.tuwien.ac.at/~florian/" >Florian Libisch</a> (TU-D Speaker),
  <a href="https://www.pranavsingh.co.uk">Pranav Singh</a>.


  <a href="https://github.com/newbisi/newbisi.github.io/raw/main/pdf/CV_TobiasJawecki.pdf"> <i class="fa fa-file-pdf-o"></i>  Download CV</a>

content:
  - title: Research interests
    layout: text
    content:
      Practical error estimates for Krylov approximations to the action of matrix exponentials.
      Adaptive Magnus-Krylov integrators. Geometric numerical integration. Time propagation of quantum systems.
      Rational best approximation to the imaginary exponential.
      Orthogonal polynomials, orthogonal rational functions, and related Gaussian quadrature formulae in the context of Krylov techniques.
      Variants of the near-best approximation property of rational Krylov methods.

  - title: Software
    layout: list
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: rexpi
        link: https://github.com/newbisi/rexpi
        link_text: Github page
        description: | # this will include new lines to allow paragraphs
          A Python package providing algorithms to approximate the unitary exponential function with a focus on unitary best approximations. Also available in the pypi package manager <a href="https://pypi.org/project/rexpi/">link</a>. This package is still under development.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: adaptive Magnus-Krylov propagators
        link: https://github.com/newbisi/mkprop
        link_text: Github page
        description: | # this will include new lines to allow paragraphs
          A Python package providing adaptive Magnus-Krylov and Krylov methods for time integration of Schrödinger-type equations. Also available in the pypi package manager <a href="https://pypi.org/project/mkprop/">link</a>. This package is still under development.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: smallexpimv
        link: https://github.com/newbisi/smallexpimv
        link_text: Github page
        description: | # this will include new lines to allow paragraphs
          A Python package providing some subroutines for Krylov propagators. The aim of this package is mostly to test f2py implementations using blas and lapack libraries in the pypi package manager, see also <a href="https://pypi.org/project/smallexpimv">link</a>, still under development.

  - title: Publication List
    layout: list
    content:

      - layout: top
        border: 0
        title: Preprints
        description: |
          - T. Jawecki. A review of the separation theorem of Chebyshev-Markov-Stieltjes for polynomial and some rational Krylov subspaces, 2022.
            preprint at <a href="https://arxiv.org/abs/2205.01535">https://arxiv.org/abs/2205.01535</a>
            <a href="https://arxiv.org/pdf/2205.01535"> <i class="fa fa-file-pdf-o"></i> pdf</a>
            <a href="https://github.com/newbisi/newbisi.github.io/raw/main/bibentries/Ja22preprint.bib"> <i class="fa fa-quote-left"></i> bib</a>
          - T. Jawecki and P. Singh. Unitary rational best approximations to the exponential function, 2023.
            preprint at <a href="https://arxiv.org/abs/2312.13809">https://arxiv.org/abs/2312.13809</a>
            <a href="https://arxiv.org/pdf/2312.13809"> <i class="fa fa-file-pdf-o"></i> pdf</a>
            <a href="https://github.com/newbisi/newbisi.github.io/raw/main/bibentries/JS23preprint.bib"> <i class="fa fa-quote-left"></i> bib</a>

      - layout: top
        border: 0
        title: Papers in Scientific Journals
        description: |
          {: reversed="reversed"}
          6. T. Jawecki and P. Singh.
            Unitarity of some barycentric rational approximants.
            *IMA J. Numer. Anal.*, 2023.
            <a href="https://academic.oup.com/imajna/advance-article/doi/10.1093/imanum/drad066/7246874?guestAccessKey=364aee1b-b478-4d19-b4d7-0b0ce35e34c0">doi:10.1093/imanum/drad066</a>
            <a href="https://academic.oup.com/imajna/advance-article-pdf/doi/10.1093/imanum/drad066/51237009/drad066.pdf?guestAccessKey=364aee1b-b478-4d19-b4d7-0b0ce35e34c0"> <i class="fa fa-file-pdf-o"></i> pdf</a>
            <a href="https://github.com/newbisi/newbisi.github.io/raw/main/bibentries/JS23.bib"> <i class="fa fa-quote-left"></i> bib</a>
          5. W. Auzinger, J. Dubois, K. Held, H. Hofstätter, T. Jawecki, A. Kauch, O. Koch, K. Kropielnicka, P. Singh, and C. Watzenböck.
            Efficient Magnus-type integrators for solar energy conversion in Hubbard models.
            *J. Comput. Math. Data Sci.*, 2:100018, 2022.
            <a href="https://doi.org/10.1016/j.jcmds.2021.100018">doi:10.1016/j.jcmds.2021.100018</a>
            <a href="https://www.sciencedirect.com/science/article/pii/S2772415821000092/pdfft?pid=1-s2.0-S2772415821000092-main.pdf"> <i class="fa fa-file-pdf-o"></i> pdf</a>
            <a href="https://github.com/newbisi/newbisi.github.io/raw/main/bibentries/Kochetal22.bib"> <i class="fa fa-quote-left"></i> bib</a>
          4. T. Jawecki.
            A study of defect-based error estimates for the Krylov approximation of phi-functions.
            *Numer. Algorithms*, 90(1):323--361, 2022.
            <a href="https://doi.org/10.1007/s11075-021-01190-x">doi:10.1007/s11075-021-01190-x</a>
            <a href="https://link.springer.com/content/pdf/10.1007/s11075-021-01190-x.pdf"> <i class="fa fa-file-pdf-o"></i> pdf</a>
            <a href="https://github.com/newbisi/newbisi.github.io/raw/main/bibentries/Ja22.bib"> <i class="fa fa-quote-left"></i> bib</a>
          3. W. Auzinger, T. Jawecki, O. Koch, P. Pukach, R. Stolyarchuk, and E.B. Weinmüller.
            Some aspects on [numerical] stability of evolution equations of stiff type; use of computer algebra.
            In *2021 IEEE XVII th International Conference on the Perspective Technologies and Methods in MEMS Design (MEMSTECH)*, pages 180--184, 2021.
            <a href="https://doi.org/10.1109/memstech53091.2021.9468055">doi:10.1109/memstech53091.2021.9468055</a>
            <a href="https://github.com/newbisi/newbisi.github.io/raw/main/bibentries/AJKPSW21.bib"> <i class="fa fa-quote-left"></i> bib</a>
          2. C. Schattauer, L. Linhart, T. Fabian, T. Jawecki, W. Auzinger, and F. Libisch.
            Graphene quantum dot states near defects.
            *Phys. Rev. B*, 102:155430, 2020.
            <a href="https://doi.org/10.1103/PhysRevB.102.155430">doi:10.1103/PhysRevB.102.155430</a>
            <a href="https://github.com/newbisi/newbisi.github.io/raw/main/bibentries/SLFJAL20.bib"> <i class="fa fa-quote-left"></i> bib</a>
          1. T. Jawecki, W. Auzinger, and O. Koch.
            Computable upper error bounds for Krylov approximations to matrix exponentials and associated phi-functions.
            *BIT*, 60(1):157--197, 2020.
            <a href="https://doi.org/10.1007/s10543-019-00771-6">doi:10.1007/s10543-019-00771-6</a>
            <a href="https://link.springer.com/content/pdf/10.1007/s10543-019-00771-6.pdf"> <i class="fa fa-file-pdf-o"></i> pdf</a>
            <a href="https://github.com/newbisi/newbisi.github.io/raw/main/bibentries/JAK20.bib"> <i class="fa fa-quote-left"></i> bib</a>

      - layout: top
        border: 0
        title: Theses
        description: |
          - T. Jawecki.
            Krylov techniques and approximations to the action of matrix exponentials.
            Ph.D thesis, TU Wien, Austria, 2022.
            <a href="https://doi.org/10.34726/hss.2022.45083"> doi:10.34726/hss.2022.45083 </a>
            <a href="https://repositum.tuwien.at/bitstream/20.500.12708/139207/1/Jawecki%20Tobias%20-%202022%20-%20Krylov%20techniques%20and%20approximations%20to%20the%20action%20of...pdf"> <i class="fa fa-file-pdf-o"></i> pdf</a>
            <a href="https://github.com/newbisi/newbisi.github.io/raw/main/bibentries/Ja22thesis.bib"> <i class="fa fa-quote-left"></i> bib</a>
          - T. Jawecki. Bifurcation analysis via numerical continuation for nonlinear fourth-order partial differential equations. Diploma thesis, TU Wien, 2017.
            <a href="https://doi.org/10.34726/hss.2017.42161"> doi:10.34726/hss.2017.42161 </a>
            <a href="https://repositum.tuwien.at/bitstream/20.500.12708/2214/2/Jawecki%20Tobias%20-%202017%20-%20Bifurcation%20analysis%20via%20numerical%20continuation%20for...pdf"> <i class="fa fa-file-pdf-o"></i> pdf</a>
            <a href="https://github.com/newbisi/newbisi.github.io/raw/main/bibentries/Ja17thesis.bib"> <i class="fa fa-quote-left"></i> bib</a>



# Footer
footer_show_references: true
references_title: using sproogen/modern-resume-theme

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
